### ISSUE TITLE
Need to be fixed

### ISSUE THREAD

**Issue by jsy0404** [BlaCkinkGJ/Flash-Translation-Layer#24]
https://github.com/BlaCkinkGJ/Flash-Translation-Layer/blob/827996c33305a35d83d9e2497ca37de7b8beaa25/ftl/page/page-write.c#L119

with

https://github.com/BlaCkinkGJ/Flash-Translation-Layer/pull/21

**Comment by BlaCkinkGJ** [comment]
Thanks for the suggestion. You are right. The type of sector is not equal to each other. I will check all of them and make it to `uint64_t` or `sector_t`.

**Comment by BlaCkinkGJ** [comment]
If I am not fixing this, this may generate some register errors in the ARM machine 🤔

**Comment by BlaCkinkGJ** [comment]
If I am not fixing this, this may generate some register errors in the ARM machine. 🤔
